import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import CrearCuenta from "./crearCuenta/page"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <> 
      <CrearCuenta/>
      
      </>
      </body>
    </html>
  )
}
